### ISSUE TITLE
SVN Support 

### ISSUE THREAD

**Issue by rmpestano** [rmpestano/last-changes-plugin#1]
As diff2html support unified diffs, we can add support to svn.  

[SVNKit](http://stackoverflow.com/questions/13414037/how-to-get-the-changed-list-between-revision-numbers-of-svn-in-java) can be used to generate svn diffs, example: https://gist.github.com/cliffdarling/2360866

**Comment by rmpestano** [comment]
there is a problem when running a svn based job:

```
Building in workspace D:\projetos\last-changes-plugin\work\jobs\abc\workspace
FATAL: org/jenkinsci/remoting/RoleSensitive
java.lang.NoClassDefFoundError: org/jenkinsci/remoting/RoleSensitive
	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:895)
	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:833)
	at hudson.scm.SCM.checkout(SCM.java:488)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1253)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:622)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
	at hudson.model.Run.execute(Run.java:1740)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.remoting.RoleSensitive
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1375)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1325)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1078)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

**Comment by rmpestano** [comment]
The error above only occours on test environment (mvn hpi run on project root). The same version of Jenkins works without any issue, see image below:

![svn-working](https://cloud.githubusercontent.com/assets/1592273/16567429/20164178-41f5-11e6-8216-385307b1b10d.png)
